### PR TITLE
Be more robust when converting

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Could you add a test that fails with the previous version, please?

**Comment by mitar** [comment]
OK.

**Comment by diasdavid** [comment]
Going to go ahead and merge this one. Agree with @dignifiedquire, it would be great to have a test, but since it is a one line change that won't provoke any new failures, I'll go ahead and unblock it.

**Comment by mitar** [comment]
Oh, thanks.

**Pull request merged**
