### PR TITLE
chore: remove redundant deps

### PR DESCRIPTION
**Pull request by achingbrain**
There seem to be some unused deps in the package.json file so we should remove them.

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
@vmx can you patch & release please?

**Comment by vmx** [comment]
The CI failure seems real. @achingbrain do you have a look or should I?

**Comment by achingbrain** [comment]
It was real but solved by a transitive dependency update - we're pulling web-encoding out of the stack because the type/browser/main/exports thing is too fragile and we don't need it anyway since TextEncoder/Decoder are global in all environments we support.

**Review by vmx — APPROVED** [review]

**Comment by vmx** [comment]
Released!

**Pull request merged**
