### PR TITLE
feat: add defaultHashAlg

### PR DESCRIPTION
**Pull request by richardschneider**
See https://github.com/ipld/interface-ipld-format/issues/37

### CODE REVIEW

**Comment by richardschneider** [comment]
Looks like the CircleCI failure is a pre-existing problem.  Why is this project even using `leveldown`?

**Comment by vmx** [comment]
`npm ls` shows that `leveldown` is used by `ipfs-repo`. The version we use is not compatible with Node.js 10. Let me upgrade the dependencies of `js-ipld-dag-pb` to get CI green.

**Comment by richardschneider** [comment]
So why is this package using `ipfs-repo`? Nothing in the API is doing persistence.

**Comment by vmx** [comment]
If you rebase your change and `--force-with-lease` it, the CI should be green.

**Comment by vmx** [comment]
Somehow my commit now shows up in this PR. Did you cherry-pick my commit? It would be cool if you could either rebase your original brnach on top of master, or create a new branch based on master and cherry-picking your commit on top. Afterwards force push to this `defaultHashAlg` branch.

**Comment by richardschneider** [comment]
Sorry, I've always had problems with rebasing a PR.

Could you tell me how to do it correctly?

What should I do to fix the current problem?

**Comment by vmx** [comment]
- Go to the master branch: `git checkout master`
 - Update it: `git pull`
 - Go back to your branch: `git checkout defaultHashAlg`
 - Rebase it on master: `git rebase master`
 - Force push it (`--force-with-lease` is a better `--force`): `git push origin defaultHashAlg --force-with-lease`

Then you should be good.

**Comment by richardschneider** [comment]
Thanks, It was the `push` that I did wrong.

**Comment by richardschneider** [comment]
Don't approve this yet.  Travis failed once (webwork test) and then I reran it and it passed! Also got security errors from `npm`.  I looking into it.

**Comment by vmx** [comment]
That's the reason why I let the original author merge it. So you can hold off :)

Don't be botheres about the security issues on npm. They are on the dev dependencies only and mostly AEgir related. So from my point of view it's ready to get merged.

**Comment by richardschneider** [comment]
Sounds like a reasonable workflow!

**Pull request merged**
