### PR TITLE
If link hashes to serializer are base58 encoded, then decode them [Fi…

### PR DESCRIPTION
**Pull request by atvanguard**
…xes #28]

### CODE REVIEW

**Comment by atvanguard** [comment]
Will add tests, if the current direction of the PR looks good.

**Comment by diasdavid** [comment]
@atvanguard looking good! Please move on with the tests. Thank you :)

**Comment by atvanguard** [comment]
@diasdavid added a test. Feedback welcome :)

**Comment by diasdavid** [comment]
Thank you @atvanguard and apologies for taking so much time to review

**Pull request merged**
